name: Run Python Script

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # هر 30 دقیقه

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4 pillow python-telegram-bot telebot

      - name: Execute Python Script
        run: python photo+textPers.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
